#!/usr/bin/env sh
set -e

until nc -z $MONGO_HOST $MONGO_PORT
do
    echo "Mongo is unavailable. Waiting..."
    sleep 0.5
done

echo "Mongodb is up"

cmd="$@"

if [ "$1" == "prepare" ]; then
    echo "Initializing db"
    python run.py initdb

    echo "Loading data"
    python run.py loadcsv /usr/share/data/data.csv

    shift 1
    cmd="$@"
fi

exec $cmd
